"""The device reference file an agent consults before acting.

MHS describes drivers as auto-producing "a reference file with information
about a device's general characteristics, such as what it can measure, what can
be adjusted, and what safety limits will be enforced". That is generated here
from sources already present in the codebase - the driver's channel table, its
declared capabilities, and the profile its device class supplies - so the
reference can never drift from the code that enforces it.

Two renderings: JSON for programmatic discovery, Markdown for a human (or a
model) to read in one pass.
"""

from __future__ import annotations

import time
from typing import TYPE_CHECKING

from .. import __version__

if TYPE_CHECKING:  # pragma: no cover
    from ..device import Device
    from ..models import DeviceInfo

#: Bumped when the descriptor layout changes, so a consumer can tell.
DESCRIPTOR_VERSION = "0.1"


def build_descriptor(device: Device, info: DeviceInfo) -> dict:
    """Assemble the machine-readable device description.

    The device class supplies the parts only it can know - what the hardware is
    physically capable of, and what it cannot do - through
    :meth:`Device.descriptor_profile`. Everything else (identity, channels,
    enforced limits) is derived from the driver itself, so a descriptor cannot
    drift from the code that enforces it.
    """
    table = device.channel_table()
    profile = device.descriptor_profile()

    descriptor = {
        "mhs_descriptor_version": DESCRIPTOR_VERSION,
        "generated_at": time.time(),
        "generator": f"mhs-printer/{__version__}",
        "device": {
            "id": info.device_id,
            "kind": info.kind,
            "model": info.model,
            "vendor": VENDORS.get(info.driver, info.driver),
            "driver": info.driver,
            "serial": info.serial,
            "firmware": info.firmware,
            "address": info.host,
        },
        "tags": profile.get("tags", []),
        "capabilities": [c.value for c in info.capabilities],
        "channels": table.to_list(),
        "safety": {
            "enforced_in": "driver",
            "checks": [
                "Every write is range-checked against its channel's declared limits "
                "before it reaches the hardware.",
                "Actions that move or heat the machine require an explicit confirmation flag.",
                "Prints are refused while the printer is busy or reporting a fatal/serious alert.",
                "Scheduled jobs wait for an idle printer and expire rather than starting late.",
                "Raw gcode is restricted to a safe list unless explicitly enabled.",
            ],
            "limits": {
                channel["name"]: channel["limit"]
                for channel in table.to_list()
                if channel["limit"]
            },
        },
        "cannot": profile.get("cannot", []),
    }
    # Device-class sections (a printer's build volume and resolution, a vacuum's
    # map and coverage) sit alongside the common ones rather than inside them.
    for section, payload in profile.items():
        if section not in {"tags", "cannot"}:
            descriptor[section] = payload
    return descriptor


#: Human-facing vendor names, keyed by driver.
VENDORS = {"bambu": "Bambu Lab", "roborock": "Roborock", "mock": "MHS", "mock_vacuum": "MHS"}


def descriptor_markdown(descriptor: dict) -> str:
    """Render the descriptor as a reference sheet to read before acting."""
    device = descriptor["device"]
    lines = [
        f"# {device['model']} ({device['id']})",
        "",
        f"MHS device descriptor v{descriptor['mhs_descriptor_version']} - "
        f"generated by {descriptor['generator']}",
        "",
        "## What this device is",
        "",
    ]
    lines += [f"- {tag}" for tag in descriptor["tags"]]

    if descriptor.get("capability_summary"):
        heading = descriptor.get("capability_heading", "What it can do")
        lines += ["", f"## {heading}", ""]
        lines += [f"- {item}" for item in descriptor["capability_summary"]]

    lines += [
        "",
        "## Channels",
        "",
        "| channel | access | unit | limits | description |",
        "| --- | --- | --- | --- | --- |",
    ]
    for channel in descriptor["channels"]:
        limit = channel["limit"]
        if not limit:
            bounds = "-"
        elif limit["allowed"]:
            bounds = ", ".join(limit["allowed"])
        else:
            low = f"{limit['minimum']:g}" if limit["minimum"] is not None else "-inf"
            high = f"{limit['maximum']:g}" if limit["maximum"] is not None else "inf"
            bounds = f"{low} to {high}"
        if limit and limit["requires_confirmation"]:
            bounds += " (needs confirmation)"
        lines.append(
            f"| `{channel['name']}` | {channel['access']} | {channel['unit'] or '-'} | "
            f"{bounds} | {channel['description']} |"
        )

    lines += ["", "## Safety", "", f"Enforced in the {descriptor['safety']['enforced_in']}:", ""]
    lines += [f"- {check}" for check in descriptor["safety"]["checks"]]
    lines += ["", "## What it cannot do", ""]
    lines += [f"- {item}" for item in descriptor["cannot"]]
    lines.append("")
    return "\n".join(lines)
